state_list<-c("alabama", "alaska", "arizona", "arkansas", "california", "colorado", "connecticut",
              "delaware", "florida", "georgia", "hawaii", "idaho", "illinois", "indiana", "iowa",
              "kansas", "kentucky", "louisiana", "maine", "maryland", "massachusetts", "michigan",
              "minnesota", "mississippi","missouri","montana","nebraska","nevada","new hampshire",
              "newhampshire", "new jersey", "newjersey", "new mexico", "newmexico", "new york", 
              "newyork", "north carolina","northcarolina", "north dakota", "northdakota","ohio",
              "pennsylvania", "rhode island", "rhodeisland", "south carolina", "southcarolina",
              "south dakota", "southdakota", "tennessee", "texas", "utah", "vermont", "virginia",
              "washington", "west virginia", "westvirginia", "wisconsin", "wyoming", "al", "ak",
              "az", "ar", "ca", "co", "ct", "de", "fl", "ga", "hi", "id", "il", "in", "ia","ks",
              "ky","la","me","md","ma","mi","mn","ms","mo","mt","ne","nv","nh","nj","nm","ny",
              "nc","nd", "oh", "ok","or","pa","ri","sc","sd","tn","tx","ut","vt","va","wa","wv",
              "wi","wy")


state_key <- c("alabama"="alabama", "alaska"="alaska", "arizona"="arizona", "arkansas"="arkansas", 
               "california"="california", "colorado"="colorado", "connecticut"="connecticut",
               "delaware"="delaware", "florida"="florida", "georgia"="georgia", "hawaii"="hawaii", 
               "idaho"="idaho", "illinois"="illinois", "indiana"="indiana", "iowa"="iowa",
               "kansas"="kansas", "kentucky"="kentucky", "louisiana"="louisiana", "maine"="maine", 
               "maryland"="maryland", "massachusetts"="massachusetts", "michigan"="michigan",
               "minnesota"="minnesota", "mississippi"="mississippi","missouri"="missouri",
               "montana"="montana","nebraska"="nebraska","nevada"="nevada","new hampshire"="newhampshire",
               "newhampshire"= "newhampshire", "new jersey"="newjersey", "newjersey"="newjersey", 
               "new mexico"="newmexico", "newmexico"="newmexico", "new york"="newyork", 
               "newyork"="newyork", "north carolina"="northcarolina","northcarolina"="northcarolina",
               "north dakota"="northdakota", "northdakota"="north dakota","ohio"="ohio",
               "pennsylvania"="pennsylvania", "rhode island"="rhode island", "rhodeisland"="rhode island",
               "south carolina"="southcarolina", "southcarolina"="south carolina",
               "south dakota"="southdakota", "southdakota"="southdakota", "tennessee"="tennessee", 
               "texas"="texas", "utah"="utah", "vermont"="vermont", "virginia"="virginia",
               "washington"="washington", "west virginia"="westvirginia", "westvirginia"="westvirginia",
               "wisconsin"="wisconsin", "wyoming"="wyoming", "al"="alabama", "ak"="alaska",
               "az"="arizona", "ar"="arkansas", "ca"="california", "co"="colorado", "ct"="connecticut", 
               "de"="delaware", "fl"="florida", "ga"="georgia", "hi"="hawaii", "id"="idaho", "il"="illinois",
               "in"="indiana", "ia"="iowa","ks"="kansas", "ky"="kentucky","la"="louisiana","me"="maine",
               "md"="maryland","ma"="massachusetts","mi"="michigan","mn"="minnesota","ms"="mississippi",
               "mo"="missouri","mt"="montana","ne"="nebraska","nv"="nevada","nh"="newhampshire","nj"="newjersey",
               "nm"="newmexico","ny"="newyork", "nc"="northcarolina","nd"="northdakota", "oh"="ohio",
               "ok"="oklahoma","or"="oregon","pa"="pennsylvania","ri"="rhodeisland","sc"="southcarolina",
               "sd"="southdakota","tn"="tennessee","tx"="texas","ut"="utah","vt"="vermont","va"="virginia",
               "wa"="washington","wv"="westvirginia", "wi"="wisconsin","wy"="wyoming")

